pazuzu-io/pazuzu-registry

.travis.yml, MAINTAINERS
Adding java8 to travis file
Adding myself to maintainers list
=> Set travis java to java8

.gitignore, pom.xml, src/main/resources/application.properties, src/main/resources/static/api/uriListConverter.js, src/main/resources/static/api/uriTemplateInterceptor.js, src/main/resources/static/app.js, src/main/resources/static/client.js, src/main/resources/static/css/style.css, src/main/resources/static/package.json, src/main/resources/static/webpack.config.js, src/main/resources/templates/home.html
Just adding the initial ui structure
=> Initial ui

src/main/java/org/zalando/pazuzu/exception/BadRequestException.java, src/main/java/org/zalando/pazuzu/exception/ErrorDto.java, src/main/java/org/zalando/pazuzu/exception/GlobalExceptionHandler.java, src/main/java/org/zalando/pazuzu/exception/NotFoundException.java, src/main/java/org/zalando/pazuzu/exception/ServiceException.java, src/main/java/org/zalando/pazuzu/feature/FeatureService.java, src/test/java/org/zalando/pazuzu/ContainerApiTest.java, src/test/java/org/zalando/pazuzu/FeatureApiTest.java, swagger.yaml
Added a more descriptive error message for some cases (e. g. delete features with references). Therefore added a new field to the ErrorDTO...
=> #24 add error details to exceptions and dto

src/main/java/org/zalando/pazuzu/feature/FeatureDto.java, src/main/java/org/zalando/pazuzu/feature/FeatureFullDto.java, src/main/java/org/zalando/pazuzu/feature/FeatureService.java, src/main/java/org/zalando/pazuzu/feature/FeatureToAddDto.java, src/main/java/org/zalando/pazuzu/feature/FeatureToCreateDto.java, src/main/java/org/zalando/pazuzu/feature/FeaturesResource.java, src/test/java/org/zalando/pazuzu/AbstractComponentTest.java, src/test/java/org/zalando/pazuzu/FeatureApiTest.java
- Fixed broken PUT (missing `@RequestBody` annotation and modification of testInstructions)
- Added unit test for PUT
- FIxed commented out test for fetching a sorted list
=> #62 fix not working PUT feature

docker-compose.yml
=> Fix db username when running with docker-compose

src/main/java/org/zalando/pazuzu/feature/FeaturesResource.java
Add Access-Control-Expose-Header with X-Total-Count
=> pazuzu-registry-78 Pagination API should expose Total Count Header

README.md
Updated setup guide for OSX based environment based on latest newbies setup
=> Add Docker Setup to Readme

src/main/java/org/zalando/pazuzu/config/CorsConfiguration.java
The Spring boot default ones do not allow for `PUT` and `DELETE`.
=> Set the allowed methods to all required ones.

src/main/java/org/zalando/pazuzu/feature/FeatureDto.java, src/main/java/org/zalando/pazuzu/feature/FeatureService.java, src/main/java/org/zalando/pazuzu/feature/FeaturesMetaResource.java, src/main/java/org/zalando/pazuzu/feature/FeaturesResource.java, src/test/java/org/zalando/pazuzu/FeatureApiTest.java, src/test/java/org/zalando/pazuzu/FeaturesMetaApiTest.java
=> allow case insenstive search using like queries

pom.xml
fix for [issue 134](https://github.com/zalando-incubator/pazuzu-registry/issues/134)
=> removed duplicate entry for surefire

.travis.yml
#138 Build script clean before testing.
=> Make sure travis clean before test.

src/main/java/org/zalando/pazuzu/api/FeatureServiceImpl.java, src/test/java/org/zalando/pazuzu/AbstractComponentTest.java, src/test/java/org/zalando/pazuzu/ApiAuthenticationTest.java, src/test/java/org/zalando/pazuzu/FeatureApiTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/146)
=> filling the author from the authenticated user

pom.xml, src/main/java/org/zalando/pazuzu/config/MapperConfiguration.java, src/main/java/org/zalando/pazuzu/exception/FeatureDuplicateException.java, src/main/java/org/zalando/pazuzu/exception/FeatureNotFoundException.java, src/main/java/org/zalando/pazuzu/exception/FeatureRecursiveDependencyException.java, src/main/java/org/zalando/pazuzu/exception/FeatureReferencedDeleteException.java, src/main/java/org/zalando/pazuzu/exception/FileNotFoundException.java, src/main/java/org/zalando/pazuzu/exception/ServiceException.java, src/test/java/org/zalando/pazuzu/AbstractComponentTest.java, src/test/java/org/zalando/pazuzu/ApiDiscoveryTest.java
Closes issue #152
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/153)
=> Upgrade zalando libraries

pom.xml
Closes issue #148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/156)
=> Fix maven incremental compilation.

src/main/java/org/zalando/pazuzu/api/FeatureServiceImpl.java
Fix some sonarlint issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/157)
=> Fix some sonarlint issues.

src/main/java/org/zalando/pazuzu/api/DependenciesServiceImpl.java, src/main/resources/api/swagger.yaml, src/test/java/org/zalando/pazuzu/ResolvedFeatureApiTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/159)
=> Fix typo in /dependencies result

src/main/resources/db/features/V1_1_1__java.sql, src/main/resources/db/features/V1_1_2__leinigen.sql, src/main/resources/db/features/V1_1_3__node.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/161)
=> Fixes #160 - Remove shebang from test snippets

.editorconfig, .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/163)
=> Add editorconfig and simplify gitignore

src/main/resources/api/swagger.yaml
This is part of single-sourcing swagger.yaml as dicussed https://github.com/zalando-incubator/pazuzu/issues/229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/164)
=> Cleanup of swagger.yaml

docker-compose-ci.yml, docker-compose-local.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zalando-incubator/pazuzu-registry/172)
=> Fixed name of common yml file to be included

Dockerfile, docker-compose-base.yml, docker-compose.yml, src/main/k8s/deployment.yml, src/main/k8s/ingress.yml, src/main/k8s/service.yml, src/main/resources/config/application-dev-clean.yml, src/main/resources/config/application-dev.yml, src/main/resources/config/application.yml, src/test/java/io/pazuzu/registry/AbstractComponentTest.java, src/test/resources/config/application-test.yml
* Added deployment, service and ingress definitions
* Included pgsql container to pod, allows client to talk to pgsql without authentication due to pgsql trust.
* Using alpine version on pgql
=> Add K8s manifests
